matrix:
  include:
    - language: cpp
      compiler:
        - gcc
      install:
        - "[ $CXX = g++ ] && export CXX=g++-6 || true"
      script:
        - bash test_cpp.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - g++-6

    - language: python
      python: 3.7
      script:
        - python -m unittest discover "Python/tests/problems" "*_test.py"

    - language: java
      jdk:
        - openjdk11
      before_install:
        - cd Kotlin
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
      script:
        - ./gradlew test

sudo: false
addons:
  sonarcloud:
    organization: "walterjgsp-github" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
